my_string=input('Привет Омлет')
my_string=input(len('Привет Омлет'))
my_string=input(('Привет омлет').upper())
my_string=input(('Привет омлет').lower())
my_string=input(('Привет омлет').replace(' ',''))
my_string=input(('Привет омлет')[0])
my_string=input(('Привет омлет')[-1])
