my_string=input('Привет Омлет')
print(len('Привет Омлет'))
print(('Привет омлет').upper())
print(('Привет омлет').lower())
print(('Привет омлет').replace(' ',''))
print(('Привет омлет')[0])
print(('Привет омлет')[-1])
